appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AF16N6GWDx+FVSoxUHL6HHqNLJTqOiMgIj4HzznUhFFnAjBVakRWhni87eamZxdg++cTwcx0bUQY9BUgx+bLPOcl/0nKJbNrdsQTnTP6nAwVKRZwvjFB7Kk5fRcK8d6Sixlgws/Pehy4w9bm79sXXTDRxXZAxCOxvBkRp8CWJNHhgvqoAT3IUUV1Pt0WiAPCZQEKhanQvyVpvoKt8QlWSbYBVyKjOEI1csx0urQh+TxbHFerdGBmfkM3pcbTmDdpqrAatzFiznB0v205jV1oHtl5n+8Ikog7aWBhop0diWB/8L2Fphp4KKRbfgx01r0nPAB7fgLv9LrP2AgRstZXrQ5nIli7zakXTpHY/lvF4FEje04NJSGMmj6U/PqPfo62pF/wrjwqkMuPvyCmqzPV3ZGz4CDZawn65nKaJiSMC/cj05ZYCQwUBKnP2tC9/HqlsHeQ1jJlLf8cTKcUalsDee+wOBGnHuKVJs5XKC6BydOfuGjzKKwlOzsd0qoD+Csf6K2scKbDdKqWI/+xuhOWSIjRPO3wuR+V4R/NUR4CZnASSFarPemaIysh79696ahYcn2kgsV3xNAo6bGVdcILP2ROZmsTSdLDR5qkcmDweLhr2pX04rfWbj+/zFgVv1Sd2boH1Tx529WQk3P5mem8WkJVZ+nBEHes2ktXzQkyl+I=
conda_forge_output_validation: true
